is.num = (arg) => (typeof arg === "number" && !Number.isNaN(arg) ? true : false);
is.nan = (arg) => (Number.isNaN(arg) ? true : false);
is.str = (arg) => (typeof arg === "string" ? true : false);
is.bool = (arg) => (typeof arg === "boolean" ? true : false);
is.undef = (arg) => (arg === undefined ? true : false);
is.def = (arg) => (arg !== undefined ? true : false);
is.arr = (arg) => (Array.isArray(arg) ? true : false);
is.obj = (arg) => (arg !== null && typeof arg === "object" && !Array.isArray(arg) ? true : false);
is.fun = (arg) => (typeof arg === "function" ? true : false);
is.truthy = (arg) => (!!arg ? true : false);
is.falsy = (arg) => (!arg ? true : false);